{% set name = "scmrepo" %}
{% set version = "2.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scmrepo-{{ version }}.tar.gz
  sha256: abda58245beced058f2ebbfff6e59b669fb91ab16f419d96a1587f72ed8e30d7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm >=6.3.1
  run:
    - asyncssh >=2.13.1,<3
    - dulwich >=0.21.6
    - fsspec >=2021.7.0
    - funcy >=1.14
    - gitpython >3
    - pathspec >=0.9.0
    - pygit2 >=1.14.0
    - pygtrie >=2.3.2
    - python >=3.8
    - shortuuid >=0.5.0
    - dvc-objects >=3,<4
    - dvc-http >=2.29.0

test:
  imports:
    - scmrepo
    - scmrepo.git
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/iterative/scmrepo
  summary: SCM wrapper and fsspec filesystem for Git for use in DVC
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - skshetry
    - efiop
    - pmrowla
    - dtrifiro
    - shcheklein
