{% set name = "scmrepo" %}
{% set version = "1.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scmrepo-{{ version }}.tar.gz
  sha256: d03278d6a86caa5c7f1e85918bc28ef69040a5e5fd04c97cc0eea611ea8be13c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm >=6.3.1
  run:
    - asyncssh >=2.7.1,<3
    - dulwich >=0.20.46
    - fsspec >=2021.7.0
    - funcy >=1.14
    - gitpython >3
    - pathspec >=0.9.0
    - pygit2 >=1.10.0
    - pygtrie >=2.3.2
    - python >=3.8
    - shortuuid >=0.5.0

test:
  imports:
    - scmrepo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/iterative/scmrepo
  summary: SCM wrapper and fsspec filesystem for Git for use in DVC
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - skshetry
    - efiop
    - pmrowla
    - dtrifiro
    - shcheklein
