{% set name = "scmrepo" %}
{% set version = "3.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scmrepo-{{ version }}.tar.gz
  sha256: 1eb09b8b572b434a31194e511351ab4047f1975ccddb29361c320648315edd08

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm >=6.3.1
  run:
    - aiohttp-retry >=2.5.0
    - tqdm
    - asyncssh >=2.13.1,<3
    - dulwich >=0.24.0
    - fsspec >=2024.2.0
    - funcy >=1.14
    - gitpython >3
    - pathspec >=0.9.0
    - pygit2 >=1.14.0
    - pygtrie >=2.3.2
    - python >={{ python_min }}

test:
  imports:
    - scmrepo
    - scmrepo.git
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/iterative/scmrepo
  summary: SCM wrapper and fsspec filesystem for Git for use in DVC
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - skshetry
    - efiop
    - pmrowla
    - dtrifiro
    - shcheklein
