{% set name = "scmrepo" %}
{% set version = "3.3.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scmrepo-{{ version }}.tar.gz
  sha256: 33db834d55acda842a8266f7d9450c59182a983851f6a80aa63779c7bfa60118

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools_scm >=6.3.1
  run:
    - aiohttp-retry >=2.5.0
    - tqdm
    - asyncssh >=2.13.1,<3
    - dulwich >=0.22.1
    - fsspec >=2024.2.0
    - funcy >=1.14
    - gitpython >3
    - pathspec >=0.9.0
    - pygit2 >=1.14.0
    - pygtrie >=2.3.2
    - python >=3.8

test:
  imports:
    - scmrepo
    - scmrepo.git
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/iterative/scmrepo
  summary: SCM wrapper and fsspec filesystem for Git for use in DVC
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - skshetry
    - efiop
    - pmrowla
    - dtrifiro
    - shcheklein
